apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ .Release.Name }}-eventbus
  namespace: {{ .Release.Namespace }}
spec:
  jetstream:
    version: "latest"
    replicas: 1
    persistence:
      storageClassName: standard
      accessMode: ReadWriteOnce
      volumeSize: 10Gi
    streamConfig: |
      maxMsgs: 100000
      maxBytes: 1GB
      maxAge: 72h
      replicas: 1