
minio:
  rootUser: random-minio-user
  rootPassword: password-user
  mode: standalone
  ingress:
    enabled: true
  persistence:
    size: 10Gi
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: NodePort
    nodePort: 30080
  consoleService:
    type: NodePort
    nodePort: 30081
postgresql:
  auth:
    username: p0stgr3s_user
    password: p0stgr3s_password
    database: mission_control
    enablePostgresUser: true
    postgresPassword: P0stgr3sP4ssw0rd
  primary:
    persistence:
      enabled: false
    service:
      type: NodePort
      nodePorts:
        postgresql: 30543