{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ServiceAccount*/}}
{{/*metadata:*/}}
{{/*  name: default*/}}
{{/*  namespace: {{ $.Release.Namespace }}*/}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-creator
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-workflow-creator
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-creator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $.Release.Namespace }}

{{- range $i, $flow := .Values.flows}}
{{- if $flow.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{$flow.serviceAccount}}-sa
  namespace: {{ if hasKey $flow "namespace" }}{{ $flow.namespace | default $.Release.Namespace }}{{ else }}{{ $.Release.Namespace }}{{ end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-creator
  namespace: {{ if hasKey $flow "namespace" }}{{ $flow.namespace | default $.Release.Namespace }}{{ else }}{{ $.Release.Namespace }}{{ end }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-workflow-creator
  namespace: {{ if hasKey $flow "namespace" }}{{ $flow.namespace | default $.Release.Namespace }}{{ else }}{{ $.Release.Namespace }}{{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-creator
subjects:
  - kind: ServiceAccount
    name: {{$flow.serviceAccount}}-sa
    namespace: {{ if hasKey $flow "namespace" }}{{ $flow.namespace | default $.Release.Namespace }}{{ else }}{{ $.Release.Namespace }}{{ end }}
{{- end }}
{{- end }}
